### ISSUE TITLE
unreachable executed

### ISSUE THREAD

**Issue by Kuranes** [surma/wasmphobia#10] opened 2024-05-22 07:26 UTC
on Wasm files From C++ using emscripten:
`emcc ${LINK_PARAMETERS} -s EXPORTED_FUNCTIONS="['_myOwnMain','_otherCallUpdate', ...] `
I get only "unreachable executed" on wasm files 

Those are wasm library interfaced by js code calling wasm entry point "manually" (no main)

Would there be a way to put "wasm library" by specifying library "entry points" ?

**Comment by surma** [comment] 2024-05-22 08:08
Are you able to share the .wasm file so I can reproduce the error? It shouldn’t matter that there is no `main` or anything.

**Comment by Kuranes** [comment] 2024-05-23 04:44
Sorry I'll try to make a minimal repro case then if it's not supposed to happen.

**Comment by adamscott** [comment] 2024-09-27 16:38
Hi @surma ! I'm the Web team lead developer of the @godotengine and I happen to have this same issue, when trying to debug our WASM export of the engine with debug symbols. Stripped, the template_debug build is 27.9MB, but with debug symbols, it's about 343.6MB.

It loads perfectly without debug_symbols, but it's not really interesting. It has thought he `unreachable executed` error when loading the bigger .wasm.

![image](https://github.com/user-attachments/assets/3427f5b0-3711-4b56-9b79-ae4b4e709b40)

[[iCloud] Here's the built files in a zip (that includes the .wasm)](https://www.icloud.com/iclouddrive/0f6SqvAh1g4RVNuySyvmthGmA#godot.web.template%5Fdebug.wasm32.nothreads)

Many thanks!

**Comment by surma** [comment] 2024-09-28 10:34
Thanks for providing a wasm. That lets met reproduce the error. Looking into this.

The error is caused by a display function panicking (which you can actually see in your browser DevTools. I should probably surface those warnings somewhere).

<img width="696" alt="Screenshot 2024-09-28 at 11 27 15" src="https://github.com/user-attachments/assets/6fded2e8-08b7-429c-956b-617fcd78aeac">

Looking into it with debug build, it seems that the `demangle_cpp` crate, which demangles C++ function names, is panicking for some reason. **Enabling the “Raw Symbols” option in Wasmphobia will not use that crate and flamegrapg generation will suceed.** That way you can continue your investigation. I will look into what’s going on there.

The error `The end of an address range must not be before the beginning.` is printed _a lot_. I’ll try and figure out whether that’s a decoding error or whether the DWARF data is faulty.

**Comment by surma** [comment] 2024-09-28 11:08
I whip up a (partial) fix for this in #11.

Could you both (@Kuranes @adamscott) give it a try and confirm that it works and that the flame graph looks reasonable etc?

The error `Could not extract function names for region: The end of an address range must not be before the beginning` eats that wasm file without errors, so I assume there’s a bug somewhere in `addr2line` or similar. I don’t have time right now to investigate that deeply, so if anyone wants to help, that would be very welcome!

**Comment by adamscott** [comment] 2024-09-28 16:03
> Could you both (@Kuranes @adamscott) give it a try and confirm that it works and that the flame graph looks reasonable etc?

It seems to work alright! The signatures seems OK! I'll get back to you if there's anything wrong, but so far, so good.

Thank you so much for the fast response, greatly appreciated.

**Comment by surma** [comment] 2024-09-28 17:18
Great! I’ll go ahead an merge and switch it live. 

I’ll open a separate issue for the weird function error. If anyone can manage to produce a smaller wasm that triggers that error, I’d be grateful!

**Closed** 2024-09-28 17:19 UTC
